echo "==========================="
echo "   Linux System Report"
echo "==========================="
echo ""
echo "👤 Current User: $(whoami)"
echo ""
echo "🖥 Hostname: $(hostname)"
echo ""
echo "📂 Current Directory: $(pwd)"
echo ""
echo "📅 Current Date: $(date)"
echo ""
echo "⚙️ Kernel Version: $(uname)"
echo ""
echo "💾 Disk Usage: $(df -h)"
echo ""
echo "🧠 Memory Usage: $(free -h)"
echo ""
echo "======================"